### ISSUE TITLE
Replace existing file

### ISSUE THREAD

**Issue by codyrotwein** [bskim45/fastlane-plugin-google_drive#11]
Is there a way for this plugin to replace an existing file that it already uploaded? Each time I use it, it creates a new instance of the same filename.

**Comment by bskim45** [comment]
Unfortunately no. Due to the nature of how google drive works, to overwite existing drive file, we need a different approach than `upload`, replacing the content of the existing file by specifying exact `file id` of it. (Not the file name nor drive path.)

I'll try to add this on upcoming version, but I'm not sure when it will be released.

Of course PR is always welcomed 😄

**Comment by codyrotwein** [comment]
Got it thanks!

**Comment by bskim45** [comment]
I've introduced new action `update_google_drive_file` in `v0.5.0`. Please check out!

**Comment by codyrotwein** [comment]
works great thank you!

**Comment by zkrige** [comment]
@bskim45 

I wrote a grunt script to do this for a different app, but the logic could probably work here

- search drive for `filename`
- if exists, then get id and update
- if not exists, then upload / create file

would it be possible to implement something like this? I'd be happy to share the js code I wrote that does all this if it helps
